### ISSUE TITLE
Synthetic worm pose

### ISSUE THREAD

**Issue by wenquan** [iteal/wormpose#13]
Thanks a lot for developing wormpose!

When trying out our own dataset in the Tierpsy tracker format, we are stuck in the synthetic image step. The generated image clearly does not look like a worm. Note that we can successfully load the raw dataset and visualize them in wormpose.

Do you have any idea how to proceed?  Does the generative neural network know how to deal with a customized dataset that look different from a standard multi-worm tracker image?

Best,
Quan

![6851636787326_ pic_hd](https://user-images.githubusercontent.com/250976/141610607-9e5db108-6095-4cbd-bff5-a06d9d28b061.jpg)

![6871636787357_ pic_hd](https://user-images.githubusercontent.com/250976/141610997-f7f371ae-86be-4b44-b01d-22050de54f15.jpg)

**Comment by iteal** [comment]
Hi Quan!

Thank you for reaching out. You are correct that the synthetic image does not look right so it is no use to go further without investigating.
I have another notebook called check_dataset that is very useful to debug the data, you can try it out here:
https://github.com/iteal/wormpose/blob/main/examples/check_dataset.ipynb
Firts run the notebook with the sample data to see what it should look like than replace with your data. I see the worm is lighter than the background so don't forget to set this variable to true.
Also note that wormpose will work better if the image has some texture, if the worm pixel values are all white then there is not a lot of information when the worm is coiling for example. Wormpose network detects a single frame, the temporal postprocessing can fix some problems but it is better that the original image is detailed enough to be able to perceive the pose in one image.

Thanks for trying wormpose and I hope you get better results soon!
Laetitia

**Comment by iteal** [comment]
Was due to the skeleton values in microns and not in pixels in the Tierpsy data which is not supported. Updated doc (https://iteal.github.io/wormpose/tierpsy.html) with more context.
