### ISSUE TITLE
WormPose check_dataset error

### ISSUE THREAD

**Issue by AmbroseX** [iteal/wormpose#14]
Thanks a lot for developing wormpose!

We get the `filename.hdf5` and `filename_featureN.hdf5` files from tierpsy software, and then check the data using `check_dataset.ipyb` in WormPose, we find that the worm's body and coordinates are not aligned in step: Check features
![5b4d46b47b34c5ce66db6962f4ad506](https://user-images.githubusercontent.com/48016446/144548956-7925a5d8-7034-4e2f-a20c-b2d96a339fe3.png)
But we check data in Tierpsy Tracker Viewer is fine like this
![ecd861667e258b59daecfdf5d96bdc7](https://user-images.githubusercontent.com/48016446/144549040-0e29b51d-23ed-41b0-829b-9b1562680d3a.png)
Then we check Your data from https://wormpose.unit.oist.jp/worm/dataset/N2_on_food/N2%20on%20food%20R_2015_07_09__15_57_54___4___1/
![4674dae7e3b5b9a9ee37fbd0cba4f3a](https://user-images.githubusercontent.com/48016446/144549239-73f3e02f-c2c9-4d14-8e84-90f5fc9b3afe.png)
Your data works fine. Then we check the files using ImageJ, we find your two files' data structure are

![ca1d675d80dd8f9f39507bfed02ebc5](https://user-images.githubusercontent.com/48016446/144549394-d23fc7ea-9fae-442a-b6f7-6e7333dcec35.png)

but our data structure is
![bd9de63cb89ef73eeebd177a51e6651](https://user-images.githubusercontent.com/48016446/144549440-54fd452d-70ed-4705-b86f-b778c81ee1ba.png)

They are missing a lot, So we think that the lack of some kind of transformation in our data causes the skeleton and image to be misaligned.
And there is our json file after you fixed.
`{
    "analysis_type": "TIERPSY_SINGLE",
    "analysis_checkpoints": [
        "COMPRESS",
        "TRAJ_CREATE",
        "TRAJ_JOIN",
        "SKE_INIT",
        "BLOB_FEATS",
        "SKE_CREATE",
        "SKE_FILT",
        "SKE_ORIENT",
        "INT_PROFILE",
        "INT_SKE_ORIENT",
        "FEAT_INIT",
        "FEAT_TIERPSY"
    ],
    "mask_min_area": 642,
    "mask_max_area": 65138,
    "thresh_C": 9,
    "thresh_block_size": 20,
    "dilation_size": 9,
    "save_full_interval": -1,
    "compression_buff": -1,
    "keep_border_data": false,
    "is_light_background": false,
    "is_extract_timestamp": true,
    "expected_fps": 95.0,
    "microns_per_pixel": 2.43,
    "mask_bgnd_buff_size": -1,
    "mask_bgnd_frame_gap": -1,
    "is_full_bgnd_subtraction": false,
    "worm_bw_thresh_factor": 1.05,
    "strel_size": 5,
    "traj_min_area": 25,
    "traj_min_box_width": 5,
    "traj_max_allowed_dist": 25,
    "traj_max_frames_gap": 0,
    "traj_area_ratio_lim": 2,
    "roi_size": -1,
    "w_num_segments": 24,
    "w_head_angle_thresh": 60,
    "resampling_N": 49,
    "max_gap_allowed_block": -1,
    "ht_orient_segment": -1,
    "filt_bad_seg_thresh": 0.8,
    "filt_max_width_ratio": 2.25,
    "filt_max_area_ratio": 6,
    "filt_min_displacement": 10,
    "filt_critical_alpha": 0.01,
    "int_save_maps": false,
    "int_avg_width_frac": 0.3,
    "int_width_resampling": 15,
    "int_length_resampling": 131,
    "int_max_gap_allowed_block": -1,
    "head_tail_int_method": "MEDIAN_INT",
    "split_traj_time": 90,
    "ventral_side": "",
    "feat_skel_smooth_window": 5,
    "feat_coords_smooth_window_s": 0.25,
    "feat_gap_to_interp_s": 0.25,
    "feat_derivate_delta_time": 0.33,
    "n_cores_used": 1,
    "nn_filter_to_use": "none",
    "path_to_custom_pytorch_model": "",
    "use_nn_food_cnt": false,
    "MWP_total_n_wells": -1,
    "MWP_whichsideup": "upright",
    "MWP_well_shape": "square",
    "MWP_well_masked_edge": 0.1
}`

Best,
Rongkang

**Comment by iteal** [comment]
Hi!
Would you mind sending me, or making available in a public place a sample of your two files filename.hdf5 and filename_featureN.hdf5 ? Of the same kind that opens correctly in the tierpsy UI and have bad features in the check_dataset notebook, it can be a short segment of less than 100 frames for example. I can check it out this way and see what is the problem.
Thank you!

**Comment by iteal** [comment]
The values were in microns and not pixel which is not supported. Added more explanation in the doc (https://iteal.github.io/wormpose/tierpsy.html) to explain how to configure Tierpsy to use pixels instead of another unit.
