### ISSUE TITLE
Cannot open file Tierpsy Tracker

### ISSUE THREAD

**Issue by JGNieto** [iteal/wormpose#16]
When trying to open a Tierpsy file from the check_dataset notebook, I get the following error:
```
ValueError                                Traceback (most recent call last)
<ipython-input-4-2b375a517e08> in <module>()
     16 # optional fields: there is an optional resize parameter to resize the images
     17 # also you can select specific videos from the dataset instead of loading them all
---> 18 dataset = load_dataset(dataset_loader, dataset_path, worm_is_lighter=worm_is_lighter)

1 frames

/usr/local/lib/python3.7/dist-packages/wormpose/dataset/features.py in calculate_crop_window_size(features)
    116     max_average_worm_length = calculate_max_average_worm_length(features)
    117     if np.isnan(max_average_worm_length):
--> 118         raise ValueError(
    119             "Can't calculate the crop window size: "
    120             "couldn't get the max average worm length in the dataset."

ValueError: Can't calculate the crop window size: couldn't get the max average worm length in the dataset. Please check the labeled features in this dataset.

```

After looking at my basename_skeletons.hdf5, I have seen the /skeleton container is composed of arrays that only contain `nan` values. Is there a way to fix this or work around it?

**Comment by iteal** [comment]
Hi!  In the Tierpsy viewer, can you open your files and see the pose on top of your images?  If yes, can you send me a short sample of your Tierpsy files (frames and features) so I can check?

**Comment by JGNieto** [comment]
Thank you for your reply. You are correct, I cannot see the pose on top of the images in the Tierpsy viewer. What might be causing this?

**Comment by iteal** [comment]
Thanks! Yes if you cannot see the skeletons in tierpsy viewer then there is nothing for wormpose to work with.
We have been using these kind of files: https://zenodo.org/record/1033554
Maybe you can compare them with yours?

**Comment by JGNieto** [comment]
Thank you.
