### ISSUE TITLE
Dataset loader not found in google colab tutorial notebook

### ISSUE THREAD

**Issue by meldefon** [iteal/wormpose#24]
Hello! Thanks for this repository. It looks very cool!

I was trying to run the tutorial notebook on google colab. Didn't change anything, just ran the cells as is, and got as far as the "Set inputs" step before I got the error 

```
NotImplementedError: Dataset loader: 'sample_data' not found in the package entry point
```

I tried changing the dataloader to "tierpsy". No luck there either. Do you have any idea what might be going on here?

Thank you!

**Comment by iteal** [comment]
Hi @meldefon ! Usually this error in Colab meant you need to restart the Runtime after installing the package wormpose with pip. Can you confirm you installed and then restarted the Runtime in google colab? Thanks!

**Comment by meldefon** [comment]
Thank you so much for getting back to me! I didn't realize I had to restart the runtime. I'm able to run those cells now - problem solved!
