### ISSUE TITLE
preprocessed image frame size

### ISSUE THREAD

**Issue by DrSamLewis** [iteal/wormpose#3]
I'm going through the WormPose 0.1.15 Tutorial Notebook in Colab (https://github.com/iteal/wormpose/blob/master/examples/tutorial_sample_data.ipynb) using your provided sample_data (https://github.com/iteal/wormpose_data.git). The tutorial ran without errors. However, when I export images_results.zip the frames are all different sizes, and thus cannot be loaded into my video player software.

This line:
print(f"The processed images are all set to the size: ({processed_image.shape[0]}px, {processed_image.shape[1]}px).")

returns this text:
"The processed images are all set to the size: (90px, 90px)."

So I do not understand why the .png files in images_results.zip are different sizes.

<img width="1275" alt="WormPose_results" src="https://user-images.githubusercontent.com/70717947/92151413-edb37700-edd5-11ea-9a08-e73215147a23.png">
<img width="1275" alt="WormPose_preprocessing" src="https://user-images.githubusercontent.com/70717947/92151420-f015d100-edd5-11ea-98eb-cafe5e48f113.png">

**Comment by iteal** [comment]
Hi @DrSamLewis !
Thank you for trying the tutorial!

The original images of this sample dataset don't have an equal size, you can view them [here](https://github.com/iteal/wormpose_data/tree/master/datasets/sample_data). You are right I modify them for the network training and prediction by cropping or extending them all to 90x90 pixels (length of the worm for this dataset). But this process also removes the background pixels by setting them to a uniform color.
To visualize the final results, I overlay the skeleton on top of the original images.

For the Tierpsy dataset, the videos are 640x480 pixels and I use for the network a crop size of 128x128 pixels focused on the worm for example. But I still want to visualize the result on the original images of 640x480.

If you really want to view this sample dataset as images of the same size, you can use ImageMagick. In Google Colab you can use:
```bash
!apt install imagemagick
```

And then to resize the images to 150x150 pixels (example):
```bash
!mogrify -format png -background black -gravity northwest -extent 150x150 experiments/sample_data/results/sample_data/images_results/*.png
```
It will look like that:
![image](https://user-images.githubusercontent.com/28520418/92191671-57e41e80-ee9f-11ea-9463-f51309ad4b02.png)

Does it answer your question?
Thanks!

**Comment by iteal** [comment]
I will close this issue if that's ok! Don't hesitate to ask more questions!
